services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/public:/app/public
      - ./data/db:/app/db
      - ./data/exports:/app/exports
    environment:
      - UPLOADS_PATH=/app/uploads
      - PUBLIC_PATH=/app/public
      - STATIC_PATH=/app/dist
      - DB_PATH=/app/db/production.sqlite3
      - EXPORTS_PATH=/app/exports
      - RACK_ENV=production
    restart: unless-stopped
